words = [
  "autocmd",
  "bigfile",
  "keymapdoc",
  "bufferline",
  "bufmap",
  "bufnr",
  "buftype",
  "catppuccin",
  "codelenses",
  "copyfile",
  "devenv",
  "direnv",
  "errnm",
  "etype",
  "filecopy",
  "fileformat",
  "filekey",
  "fnamemodify",
  "gitsigns",
  "glab",
  "globalstatus",
  "gopls",
  "hardlinks",
  "inlinedoc",
  "isdirectory",
  "iswin",
  "joinpath",
  "justinmk",
  "keymaps",
  "lazygit",
  "lnum",
  "lpeg",
  "luacheck",
  "lualine",
  "luarc",
  "neotest",
  "neovim",
  "netrw",
  "nvim",
  "nvim's",
  "oldfiles",
  "performantly",
  "pyproject",
  "pyright",
  "quickfile",
  "readblob",
  "realpath",
  "relpath",
  "ripgrep",
  "scandir",
  "startinsert",
  "statuscolumn",
  "statusline",
  "stdpath",
  "stylua",
  "sysname",
  "tabline",
  "tmux",
  "tst",
  "unc",
  "winbar",
  "xdg",
]
