# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-added-large-files" },
    { id = "trailing-whitespace" },
    { id = "end-of-file-fixer" },
    { id = "check-yaml" },
    { id = "check-toml" },
    { id = "check-json" },
    { id = "check-merge-conflict" },
    { id = "check-added-large-files" },
    { id = "mixed-line-ending" },
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.24.2"
hooks = [{ id = "gitleaks" }]

[[repos]]
repo = "https://github.com/JohnnyMorganz/StyLua"
rev = "v2.5.2"
hooks = [
  {
    id = "stylua-github",
    args = ["--config-path=stylua.toml"]
  }
]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"
hooks = [
 { id = "conventional-pre-commit",
  stages = ["commit-msg"]
  }
  ]
