-- generate-docs.lua - generate docs/PLUGINS.md from lua/plugins/*.lua.
--
-- Run with: nvim -l scripts/generate-docs.lua
--
-- Parses each plugin spec with tree-sitter to extract the repository,
-- dependencies, and whether it is configured / defines keymaps.

local script_dir = arg[0]:match("(.*[/\\])") or "./"
package.path = script_dir .. "lib/?.lua;" .. package.path
local docgen = require("docgen")

local out = {}
table.insert(out, "# Neovim Plugins Documentation")
table.insert(out, "")
table.insert(out, "This file is auto-generated by pre-commit hooks. Do not edit manually.")
table.insert(out, "")

local files = docgen.lua_files("lua/plugins", "*.lua")
local count = 0
for _, file in ipairs(files) do
  local info = docgen.plugin_info(file)
  if info then
    count = count + 1
    table.insert(out, "## " .. info.title)
    table.insert(out, "")
    if info.repo then
      table.insert(out, "- **Repository:** https://github.com/" .. info.repo)
    else
      table.insert(out, "- **Repository:** Not specified")
    end
    if #info.dependencies > 0 then
      table.insert(out, "- **Dependencies:**")
      for _, dep in ipairs(info.dependencies) do
        table.insert(out, string.format("  - [%s](https://github.com/%s)", dep, dep))
      end
    end
    table.insert(out, "- **Configured:** " .. (info.configured and "Yes" or "Basic setup"))
    if info.has_keymaps then
      table.insert(out, "- **Has keybindings:** Yes")
    end
    table.insert(out, "")
  end
end

docgen.write("docs/PLUGINS.md", table.concat(out, "\n"))
print(string.format("Generated docs/PLUGINS.md for %d plugins", count))
