#!/bin/bash
# Generate plugin documentation from Lua configuration files

set -e

DOCS_DIR="docs"
PLUGINS_DIR="lua/plugins"

# Create docs directory if it doesn't exist
mkdir -p "$DOCS_DIR"

# Function to extract plugin info from Lua files
extract_plugin_info() {
    local file="$1"
    local filename=$(basename "$file" .lua)

    echo "## $(echo $filename | sed 's/-/ /g' | sed 's/\b\w/\u&/g')"
    echo ""

    # Extract plugin URLs (github repos)
    grep -E '^\s*"[^/]+/[^"]+",?\s*$' "$file" | head -1 | sed 's/.*"\([^"]*\)".*/- **Repository:** https:\/\/github.com\/\1/' || echo "- **Repository:** Not specified"

    # Extract description comments
    grep -E '^\s*--.*' "$file" | head -3 | sed 's/^\s*--\s*/- /' | head -1

    # Extract key features from setup calls
    if grep -q "setup(" "$file"; then
        echo "- **Configured:** Yes"
    else
        echo "- **Configured:** Basic setup"
    fi

    # Extract keymaps if any
    if grep -q "keymap.set\|vim.keymap.set" "$file"; then
        echo "- **Has keybindings:** Yes"
    fi

    echo ""
}

# Generate main plugins documentation
cat > "$DOCS_DIR/PLUGINS.md" << 'EOF'
# Neovim Plugins Documentation

This file is auto-generated by pre-commit hooks. Do not edit manually.

EOF

echo "Generated on: $(date)" >> "$DOCS_DIR/PLUGINS.md"
echo "" >> "$DOCS_DIR/PLUGINS.md"

# Process each plugin file
for file in "$PLUGINS_DIR"/*.lua; do
    if [ -f "$file" ]; then
        extract_plugin_info "$file" >> "$DOCS_DIR/PLUGINS.md"
    fi
done

# Generate keybindings documentation
cat > "$DOCS_DIR/KEYBINDINGS.md" << 'EOF'
# Keybindings Documentation

This file is auto-generated by pre-commit hooks. Do not edit manually.

EOF

echo "Generated on: $(date)" >> "$DOCS_DIR/KEYBINDINGS.md"
echo "" >> "$DOCS_DIR/KEYBINDINGS.md"

# Extract keybindings from all Lua files
echo "## Plugin Keybindings" >> "$DOCS_DIR/KEYBINDINGS.md"
echo "" >> "$DOCS_DIR/KEYBINDINGS.md"

find lua/ -name "*.lua" -exec grep -Hn "keymap\.set\|vim\.keymap\.set" {} \; | \
    sed 's/.*keymap\.set("[^"]*",\s*"[^"]*",.*desc\s*=\s*"\([^"]*\)".*/- \1/' | \
    grep -v "^-\s*$" | sort -u >> "$DOCS_DIR/KEYBINDINGS.md" 2>/dev/null || echo "- No keybindings with descriptions found" >> "$DOCS_DIR/KEYBINDINGS.md"

echo ""
echo "Generated documentation in $DOCS_DIR/"
