#!/bin/bash
# Generate plugin documentation from Lua configuration files

set -e

DOCS_DIR="docs"
PLUGINS_DIR="lua/plugins"

# Create docs directory if it doesn't exist
mkdir -p "$DOCS_DIR"

# Function to extract plugin info from Lua files
extract_plugin_info() {
    local file="$1"
    local filename=$(basename "$file" .lua)

    echo "## $(echo $filename | sed 's/-/ /g' | sed 's/\b\w/\u&/g')"
    echo ""

    # Extract plugin URLs (github repos)
    grep -E '^\s*"[^/]+/[^"]+",?\s*$' "$file" | head -1 | sed 's/.*"\([^"]*\)".*/- **Repository:** https:\/\/github.com\/\1/' || echo "- **Repository:** Not specified"

    # Extract description comments
    grep -E '^\s*--.*' "$file" | head -3 | sed 's/^\s*--\s*/- /' | head -1

    # Extract dependencies
    local deps_section=$(awk '/dependencies\s*=\s*{/,/^\s*}/' "$file" 2>/dev/null)
    if [ -n "$deps_section" ]; then
        local deps=$(echo "$deps_section" | grep -oE '"[^/]+/[^"]+"' | tr -d '"' | sort -u)
        if [ -n "$deps" ]; then
            echo "- **Dependencies:**"
            echo "$deps" | while IFS= read -r dep; do
                [ -n "$dep" ] && echo "  - [$dep](https://github.com/$dep)"
            done
        fi
    fi

    # Extract key features from setup calls
    if grep -q "setup(" "$file"; then
        echo "- **Configured:** Yes"
    else
        echo "- **Configured:** Basic setup"
    fi

    # Extract keymaps if any
    if grep -q "keymap.set\|vim.keymap.set" "$file"; then
        echo "- **Has keybindings:** Yes"
    fi

    echo ""
}

# Generate main plugins documentation
cat > "$DOCS_DIR/PLUGINS.md" << 'EOF'
# Neovim Plugins Documentation

This file is auto-generated by pre-commit hooks. Do not edit manually.

EOF



# Process each plugin file
for file in "$PLUGINS_DIR"/*.lua; do
    if [ -f "$file" ]; then
        extract_plugin_info "$file" >> "$DOCS_DIR/PLUGINS.md"
    fi
done

# Generate keybindings documentation
cat > "$DOCS_DIR/KEYBINDINGS.md" << 'EOF'
# Keybindings Documentation

This file is auto-generated by pre-commit hooks. Do not edit manually.

EOF



# Extract keybindings from all Lua files
echo "## Plugin Keybindings" >> "$DOCS_DIR/KEYBINDINGS.md"
echo "" >> "$DOCS_DIR/KEYBINDINGS.md"
echo "| Key | Description | Source |" >> "$DOCS_DIR/KEYBINDINGS.md"
echo "|-----|-------------|--------|" >> "$DOCS_DIR/KEYBINDINGS.md"

# Extract keybindings with their descriptions and source files with line numbers
for file in $(find lua/ -name "*.lua"); do
    # Get line numbers where keymap.set( starts (with opening paren to be precise)
    grep -nE 'keymap\.set\(' "$file" 2>/dev/null | while read -r line; do
        lineno=$(echo "$line" | cut -d: -f1)
        # Read from that line and join next few lines to capture multi-line definitions
        content=$(sed -n "${lineno},$((lineno+5))p" "$file" | tr '\n' ' ')
        if echo "$content" | grep -qE 'desc\s*=\s*"[^"]+"'; then
            key=$(echo "$content" | sed -E 's/.*keymap\.set\(\s*"[^"]*"\s*,\s*"([^"]+)".*/\1/')
            desc=$(echo "$content" | sed -E 's/.*desc\s*=\s*"([^"]+)".*/\1/')
            echo "| \`$key\` | $desc | [$file#L$lineno]($file#L$lineno) |"
        fi
    done
done | sort -u -t'|' -k2,3 >> "$DOCS_DIR/KEYBINDINGS.md" 2>/dev/null || echo "| - | No keybindings found | - |" >> "$DOCS_DIR/KEYBINDINGS.md"

echo ""
echo "Generated documentation in $DOCS_DIR/"
