return {
  "onsails/lspkind.nvim",
  config = function()
    require("lspkind").init({
      mode = "symbol_text",
      preset = "codicons",
      symbol_map = {
        Text = "󰉿",
        Method = "󰆧 ",
        Function = "󰊕 ",
        Constructor = " ",
        Field = " ",
        Variable = "󰆧 ",
        Class = "󰠱",
        Interface = "󰕘",
        Module = "",
        Property = " ",
        Unit = "󰑭",
        Value = "󰎠",
        Enum = "󰕘",
        Keyword = "󰌋",
        Snippet = "",
        Color = "󰏘",
        File = "󰈙",
        Reference = "󰈇",
        Folder = "󰉋",
        EnumMember = " ",
        Constant = "󰏿 ",
        Struct = "󰌗 ",
        Event = " ",
        Operator = "󰆕 ",
        TypeParameter = "󰊄 ",
        -- Terraform specific
        Resource = "󱇶",
        DataSource = "󰠶",
        Provider = "󰅶",
        -- Additional types
        Namespace = "󰌗",
        Package = " ",
        String = "󰀬 ",
        Number = "󰎠 ",
        Boolean = "◩ ",
        Array = "󰅪 ",
        Object = "󰅩 ",
        Key = "󰌋 ",
        Null = "󰟢 ",
      },
      menu = {
        lua = "[Lua]",
        python = "[Python]",
        javascript = "[JS]",
        typescript = "[TS]",
        go = "[Go]",
        terraform = "[Terraform]",
        json = "[JSON]",
        yaml = "[YAML]",
        sh = "[Shell]",
        bash = "[Bash]",
        html = "[HTML]",
        css = "[CSS]",
        markdown = "[MD]",
      },
    })
  end,
}
